
server:
  port: 8083

spring:
  application:
    name: client-feign

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
feign:
  hystrix:
    #开启断路器
    enabled: true

